### PR TITLE
Removed unneeded export

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by JLTastet** [comment]
Looks good to me!

Do you know if `export ⋅, cross, ×, norm, normalize` is still needed? It's been a while since I learned about exports in Julia...

**Comment by Moelf** [comment]
yeah, they are provided by `LinearAlgebra` std so they need to be exported. BTW [we're using](https://github.com/tamasgal/UnROOT.jl/pull/41) your LV for our `.root` file reading, thanks a lot for your elegant and fast LorentzVector!

image

**Comment by JLTastet** [comment]
Nice to see that this is used by `UnROOT`! Just make sure to specify a version range (0.4.x), since there is a chance that the API might change in the future (there used to be some discussions about "rebasing" it on top of `StaticArrays`). However, I am unlikely to (purposely) introduce breaking changes myself (at least for now), unless there is interest from `UnROOT` or other projects for a better API.

**Comment by JLTastet** [comment]
If you can bump the version to 0.4.2 in the `Project.toml`, I'll merge your PR.

**Comment by Moelf** [comment]
StaticArrays shouldn't give you any speed up when all your fields are typed like they are now. A NTuple (static array) is as fast as a NamedNTuple (your struct).

You can, however, subtype AbstractVector maybe. But that just makes things confusing :(  since people never remember what's the order of `xyzt`

**Comment by JLTastet** [comment]
> You can, however, subtype AbstractVector maybe. But that just makes things confusing :( since people never remember what's the order of xyzt

Yes, I agree with you. Let's leave it as it is for now.

Thanks again for your contribution!

**Pull request merged**
