### PR TITLE
abbreviate printing

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by JLTastet** [comment]
I’d rather use `Vec4` instead of `LV` for consistency with the shorthand constructor, so that evaluating the printed vector re-constructs an identical `LorentzVector`.

Alternatively, do you know if `Base.show` can be overloaded in user code?

**Comment by Moelf** [comment]
>Alternatively, do you know if Base.show can be overloaded in user code?

considered piracy

**Comment by Moelf** [comment]
it's Vec4 now

**Comment by JLTastet** [comment]
Is there any reason besides getting a shorter output in the REPL? Just trying to understand.

For non-REPL printing, using a custom function (not `Base.show`) is clearly the way, and I have occasionally done that.

If it’s just for the REPL, I think piracy is fine here (rather than changing the default for everyone).

**Comment by Moelf** [comment]
>Is there any reason besides getting a shorter output in the REPL? Just trying to understand.

we often have a vector vector of `LV` as a column in a .root file.

**Comment by JLTastet** [comment]
Is the problem just about printing, or does ROOT use `Base.show` when serialising the Lorentz vectors? (Sorry, I don’t have so much experience with ROOT, I mostly use Arrow et al. nowadays.)

**Comment by Moelf** [comment]
just printing. And I was trying to avoid piracy in UnROOT.jl

**Comment by JLTastet** [comment]
I see. Wouldn’t a more generic solution be to support abbreviations for commonly-used types in UnROOT.jl? That could be used beyond just `LorentzVectors` -> `Vec4`, e.g. `Float64` -> `F64`, `Complex{Float64}` -> `CF64`, etc...

It seems to me that this could be implemented by defining either a custom method or a three-argument `Base.show`, in the spirit of `Base.show(::IO, ::MIME"text/plain", ::MyType)`, but with a custom type (e.g. `TypeAbbrev`) instead of the MIME type. And defaulting to `Base.show` if the custom method is not defined.

The main reason why I am hesitating a bit to change the default printing of `LorentzVector` is that it is more explicit (and Googleable) than e.g. `Vec4` when returned by a random function, and that the printed string will be long anyway because it contains four floats.

Now, it’s true that in the context of HEP, it is quite clear that `Vec4` denotes a Lorentz vector and `Vec3` a Euclidean 3d vector. Since this package is unlikely to be used outside of HEP, I’d be open to using `Vec3`/`Vec4` everywhere by default and keeping the full names `SpatialVector`/`LorentzVector` just for backward compatibility (possibly deprecating them). That’s definitely a possibility if there is enough interest, especially considering that the only two public packages that currently depend on it are part of JuliaHEP.

**Comment by Moelf** [comment]
>I see. Wouldn’t a more generic solution be to support abbreviations for commonly-used types in UnROOT.jl? That could be used beyond just LorentzVectors -> Vec4, e.g. Float64 -> F64, Complex{Float64} -> CF64, etc...

I'm trying to avoid it because it is type piracy.

>Now, it’s true that in the context of HEP, it is quite clear that Vec4 denotes a Lorentz vector and Vec3 a Euclidean 3d vector. Since this package is unlikely to be used outside of HEP, I’d be open to using Vec3/Vec4 everywhere by default and keeping the full names SpatialVector/LorentzVector just for backward compatibility (possibly deprecating them). That’s definitely a possibility if there is enough interest, especially considering that the only two public packages that currently depend on it are part of JuliaHEP.

I think at some point we will just need to re-base LorentzVectorHEP on out own type to avoid confusion and type piracy.

**Comment by JLTastet** [comment]
> I'm trying to avoid it because it is type piracy.

Would it be? I was not thinking of defining type aliases (e.g. `const Vec4 = LorentzVectors`) or overriding methods from Base, but rather just to change the way common types are _displayed_ in UnROOT.

> I think at some point we will just need to re-base LorentzVectorHEP on out own type to avoid confusion and type piracy.

That’s also fair. The code is open-source, after all :)

I’d actually consider adding some other collaborators/maintainers to this repository, but the vision I had was to keep the code as simple and generic as possible (e.g. adding constructors & views for cylindrical coordinates, but not necessarily a separate type unless it can really justify itself, e.g. by improving performance or accuracy, and is very well tested). While LorentzVectorHEP seems to be more LHC-focused, with a number of dedicated methods that wouldn’t necessarily be as useful for e.g. Monte-Carlo simulations, beam-dump experiments, neutrino telescopes, etc...

So, while I’d be happy to let more people contribute directly to this repository and revive it a bit, if the goal is to have a LHC-optimised type that matches the C++ ROOT type, it might indeed be better to define your own type over which you will have full control. If needed, conversions can be trivially defined if compatibility is required.

**Comment by Moelf** [comment]
>overriding methods from Base, but rather just to change the way common types are displayed in UnROOT.

I don't own `Base.show` and I don't own `LorentzVectors.jl`, that's type piracy.

- - -
>adding constructors & views for cylindrical coordinates, but not necessarily a separate type unless it can really justify itself,

how about avoid allocating tens of GB when you read root files that stores `pt, eta, phi, m` on disks?

**Comment by JLTastet** [comment]
> I don't own `Base.show` and I don't own `LorentzVectors.jl`, that's type piracy.

But you own UnROOT, right? So you could use some pretty-print method with `Base.show` only used as a fallback?

> how about avoid allocating tens of GB when you read root files that stores `pt, eta, phi, m` on disks?

That’s a fair point, but I think it just shows that ROOT types have specific requirements, and that it would be better and more future-proof to use you own types for that.

You are more than welcome to reuse any parts of the code from this repo (except of course the `Project.toml` to prevent conflicts).

**Comment by Moelf** [comment]
>But you own UnROOT, right? So you could use some pretty-print method with Base.show only used as a fallback?

The method one needs to overload is `Base.show(::IO, ::MIME, ::LorentzVector)`. I can't afford to re-implement `base/showarray.jl` from Julia

**Comment by JLTastet** [comment]
I see! I didn’t understand in the first message where the difficulty came from, but indeed `showarray.jl` probably isn’t very fun to reimplement.

In any case, since the requirements for your type seem to be quite tightly coupled to ROOT, I think that from a software engineering point of view, it fully makes sense to develop it within UnROOT itself.

The present package might still receive some minor quality-of-life improvements (starting with merging the `loose-typing` branch once I get to write the tests with some non-trivial types, e.g. Pauli matrices), but for MC/theory use I feel like I am already reaching its limits. Any proper update would likely need to support full tensor indexing (including spinor indices). That would probably go to a new package. Whether I will ever get the time and a reason to write it is another issue 😅

**Comment by JLTastet** [comment]
Alternatively, since any major upgrades on my side would likely go to a new package, what I can do is make `v0.5.x` a LTS version, then transfer the repo to JuliaHEP and we can start from here.

It really depends on whether you want to keep Lorentz vectors separate from the core UnROOT functionality (and integrate them within the broader JuliaHEP ecosystem, with the stability/testing constraints that it implies) or whether you see them as a ROOT-focused data type, in which case you most likely want to have your own type over which you retain full control.

**Comment by Moelf** [comment]
we have some success in re-using the LorentzVectorHEP.jl: https://github.com/JuliaHEP/JetReconstruction.jl/pull/31/files#diff-72ed386c2a0cd1d23c0968297e70023ed98c22490d146dd89fc91f48369bad4dR21

I don't think it's meant to be only for reading root files. My preference would be for it to be https://github.com/scikit-hep/vector but with less bloat. Which is to say it should serve experimental needs well, worry less about theoy/pheno application.

**Pull request closed without merging**
